from .st_gcn_aaai18 import ST_GCN_18,ST_GCN_learnimportance1
from .st_gcn_LIN2 import ST_GCN_LIN2
from .st_gcn_LIN3 import ST_GCN_LIN3
from .ALN import ST_GCN_ALN
from .ALN1 import ST_GCN_ALN1
from .ALN2 import ST_GCN_ALN2
from .ALN3 import ST_GCN_ALN3
from .ALN4 import ST_GCN_ALN4
from .ALN5 import ST_GCN_ALN5
from .ALN6 import ST_GCN_ALN6
from .ALN7 import ST_GCN_ALN7
from .ALN8 import ST_GCN_ALN8
from .ALN9 import ST_GCN_ALN9
from .ALN10 import ST_GCN_ALN10
from .ALN11 import ST_GCN_ALN11
from .ALN12 import ST_GCN_ALN12
from .ALN13 import ST_GCN_ALN13
from .ALN14 import ST_GCN_ALN14

from .ALN15 import ST_GCN_ALN15
from .ALN16 import ST_GCN_ALN16
from .ALN17 import ST_GCN_ALN17
from .ALN18 import ST_GCN_ALN18
from .ALN19 import ST_GCN_ALN19
from .ALN20 import ST_GCN_ALN20
from .ALN21 import ST_GCN_ALN21
from .ALN22 import ST_GCN_ALN22
from .ALN23 import ST_GCN_ALN23
from .ALN24 import ST_GCN_ALN24
from .ALN25 import ST_GCN_ALN25
from .ALN26 import ST_GCN_ALN26
from .ALN27 import ST_GCN_ALN27
from .ALN28 import ST_GCN_ALN28
from .ALN29 import ST_GCN_ALN29
from .ALN30 import ST_GCN_ALN30
from .ALN31 import ST_GCN_ALN31
from .ALN32 import ST_GCN_ALN32
from .ALN33 import ST_GCN_ALN33
from .ALN34 import ST_GCN_ALN34
from .hrnet import HRNet
