from .st_gcn_aaai18 import ST_GCN_18,ST_GCN_niu,ST_GCN_ones,ST_GCN_learnimportance1
from .st_gcn_LIN2 import ST_GCN_LIN2
from .st_gcn_LIN3 import ST_GCN_LIN3
from .ALN import ST_GCN_ALN
from .ALN1 import ST_GCN_ALN1
from .ALN2 import ST_GCN_ALN2
from .ALN3 import ST_GCN_ALN3
from .ALN4 import ST_GCN_ALN4
from .ALN5 import ST_GCN_ALN5
from .ALN6 import ST_GCN_ALN6
from .ALN7 import ST_GCN_ALN7
from .ALN8 import ST_GCN_ALN8
from .hrnet import HRNet
